name: lint and unit test
permissions:
  contents: read
on:
  push:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use default Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: npm run lint
      run: |-
        npm run lint
  test:
    name: unit test
    runs-on:
      - ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use default Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: npm run test
      run: |-
        npm run test
