name: validate_build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  validate_build:
    name: validate_build
    runs-on:
      - ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build and verify MAJC dist files
      run: |-
        npm run build

    - name: Install React Example dependencies
      run: npm ci
      working-directory: ./examples/react

    - name: Build and verify Example React App
      run: npm run build
      working-directory: ./examples/react
