name: verify_build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  validate_build:
    name: validate_build
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '22.x']
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build and verify dist
      run: |-
        npm run build
    - name: Build and verify example react app
      run: |-
        npm run validate:example:build
